# Generated by Django 3.1.3 on 2021-03-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210327_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position'),
        ),
    ]
